name: GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up -d
      - run: docker tag my-fastapi-app baptisteb/ml_ops:latest
      - run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "baptisteb" --password-stdin
      - run: docker push baptisteb/ml_ops:latest
      - run: sshpass -p "Supermotdepasse!42" ssh -o StrictHostKeyChecking=no ubuntu@20.86.55.5 << 'EOF' | docker pull baptisteb/ml_ops:latest | docker run baptisteb/ml_ops:latest
