name: GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up -d
      - run: docker tag my-fastapi-app batptisteb/ml_ops:latest
      - run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
      - run: docker push batptisteb/ml_ops:latest
      - run: | 
          sshpass -p "Supermotdepasse!42" ssh -o StrictHostKeyChecking=no ubuntu@20.86.55.5 << 'EOF'
          cd baptiste.bellamy && 
          docker pull batptisteb/ml_ops:latest &&
          docker rm -f my-fastapi-app || true && 
          docker run -d -p 5010:8000 --name my-fastapi-app batptisteb/ml_ops:latest

