name: GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up -d
      - run: docker tag my-fastapi-app baptisteb/ml_ops2:latest
      - run: echo "${{ secrets.DOCKERTOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - run: docker push baptisteb/ml_ops2:latest
      - run: sshpass -p "Supermotdepasse!42" ssh -o StrictHostKeyChecking=no ubuntu@20.86.55.5 << 'EOF' | docker pull baptisteb/ml_ops2:latest | docker run baptisteb/ml_ops2:latest
      - run: docker rm -f my-fastapi-app || true && 
              docker run -d -p 5010:8000 --name my-fastapi-app baptisteb/ml_ops2:latest

